POST http://localhost:8090/sakilaAPI/ws/Actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://services.soap.api.jets.iti.gov/">
        <soap:Body>
            <jets:getAllActors />
        </soap:Body>
</soap:Envelope>

###

POST http://localhost:8090/sakilaAPI/ws/Actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://services.soap.api.jets.iti.gov/">
        <soap:Body>
            <jets:getActor>
                <actorId>19</actorId>
            </jets:getActor>
        </soap:Body>
</soap:Envelope>

###
POST http://localhost:8090/sakilaAPI/ws/Actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://services.soap.api.jets.iti.gov/">
        <soap:Body>
            <jets:createActor>
            <actor>
                <firstName>gdf</firstName>
                <lastName>gdf</lastName>
            </actor>
            </jets:createActor>
        </soap:Body>
</soap:Envelope>

###

POST http://localhost:8090/sakilaAPI/ws/Actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://services.soap.api.jets.iti.gov/">
        <soap:Body>
            <jets:deleteActor>
            <actorId>
                 2020
            </actorId>
            </jets:deleteActor>
        </soap:Body>
</soap:Envelope>

###

POST http://localhost:8090/sakilaAPI/ws/Actor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://services.soap.api.jets.iti.gov/">
        <soap:Body>
            <jets:updateActor>
            <actor>
               <id>202</id>
               <firstName>new Actor</firstName>
               <lastName>new Actor</lastName>
            </actor>
            </jets:updateActor>
        </soap:Body>
</soap:Envelope>

